### ISSUE TITLE
Cannot get Mam.fetch() Results.

### ISSUE THREAD

**Issue by iamramizansari** [iotaledger-archive/mam.client.js#55] opened 2019-04-16 20:04 UTC
Error log:
```
info: RuntimeError: unreachable
    at __rust_start_panic (wasm-function[27]:1)
    at rust_panic (wasm-function[26]:31)
    at std::panicking::rust_panic_with_hook::ha9514ccd859407a0 (wasm-function[23]:304)
    at std::panicking::continue_panic_fmt::hbdf64f9b91d66da7 (wasm-function[22]:114)
    at rust_begin_unwind (wasm-function[21]:3)
    at core::panicking::panic_fmt::hf7e0ef817f8396d5 (wasm-function[49]:70)
    at core::slice::slice_index_len_fail::ha1c53d14fa8e35d6 (wasm-function[46]:133)
    at iota_mam::mam::parse::h02cbb86a73276d2d (wasm-function[190]:1795)
    at iota_mam_parse (wasm-function[194]:108)
    at Object.decodeMessage (/Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:6722:2353)
    at /Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:6732:1020
    at Array.map (<anonymous>)
    at /Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:6732:961
    at tryCatcher (/Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:3068:587)
    at Promise._settlePromiseFromHandler (/Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:3008:13247)
    at Promise._settlePromise (/Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:3008:14689)
    at Promise._settlePromise0 (/Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:3008:15793)
    at Promise._settlePromises (/Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:3008:17564)
    at _drainQueueStep (/Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:2901:2975)
    at _drainQueue (/Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:2901:2867)
    at Async._drainQueues (/Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:2901:3112)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/iamramizansari/Desktop/fyp/iota-data-marketplace/functions/node_modules/@iota/mam/lib/mam.client.js:2901:772)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

I am trying to fetch mam but getting this error. My code:
```
const retrieveData = async (rootVal:string,keyVal:string)=> {
  Mam.init("https://nodes.devnet.iota.org");
  let datalist = [];
  console.log({params:{root:rootVal,key:keyVal}});
  const result = await Mam.fetch(rootVal, "restricted",keyVal)
      result.messages.forEach(message => {
        console.log({data:message});
        return message;
      });
  return "x"; // this line is executed.
}
```

**Comment by sobolev-alexey** [comment] 2019-05-07 09:38
Please provide your params for `rootVal` and `keyVal`, so I can run some tests

**Comment by obany** [comment] 2019-05-31 06:03
@iamramizansari I am closing this issue as we have no further details to help diagnose the issue.

**Closed as completed by obany** 2019-05-31 06:03 UTC

**Comment by johnpeng968** [comment] 2019-12-30 11:42
Hi,
I had a similar issue that I can't get Mam.fetch() to work. 
Asking for help !!! 

Thank you in advance.

The code is as following:

const Mam = require('@iota/mam')
const { asciiToTrytes, trytesToAscii } = require('@iota/converter')
const MODE = 'public'; // public, private or restricted
const SIDEKEY = ''; // Enter only ASCII characters. Used only in restricted mode

let root;
let key;

// Check the arguments
const args = process.argv;
if(args.length !=3) {
    console.log('Missing root as argument: node mam_receive.js <root>');
    process.exit();
} else if(!args[2]){
    console.log('You have entered an invalid root: '+ args[2]);
    process.exit();
} else {
    root = args[2];
}

let mamState = Mam.init('https://nodes.devnet.thetangle.org:443')
// Initialize MAM State - PUBLIC

// Set channel mode
if (MODE == 'restricted') {
    key = asciiToTrytes(SIDEKEY);
    mamState = Mam.changeMode(mamState, MODE, key);
} else {
    mamState = Mam.changeMode(mamState, MODE);
}

// Receive data from the tangle
const executeDataRetrieval = async function(rootVal, keyVal) {
        console.log ('root: ', rootVal);
        console.log ('MODE: ', MODE);
        console.log ('sideKey: ', keyVal);
    let resp = await Mam.fetch(rootVal, MODE, keyVal, function(data) {
    let json = JSON.parse(trytesToAscii(data));
    console.log(`dateTime: ${json.dateTime}, data: ${json.data}`);
   });
    executeDataRetrieval(resp.nextRoot, keyVal);
}
executeDataRetrieval(root, key);

**Comment by obany** [comment] 2019-12-30 11:57
The example code provided works OK for me, I created and published to a new MAM channel.
The root of the channel is `FJG9KMOJUAZCTHA9MYDNTPGUSRNMUHLUQW9J9PQFYPLAXYIAKPRZIJSDULJZIXHFL99JGZCV9KBFKR9KF`

the response when running your code pointing at that root was
```
root:  FJG9KMOJUAZCTHA9MYDNTPGUSRNMUHLUQW9J9PQFYPLAXYIAKPRZIJSDULJZIXHFL99JGZCV9KBFKR9KF
MODE:  public
sideKey:  undefined
dateTime: 1577706889384, data: Test
root:  NJAHYWHQAEAJBOWLBDRFEYGXRWJMKMBMCTU9GLZAUKMEVDQDFJXURDJBEJDRHQFWFNMSFFWTJDGZOIOAF
MODE:  public
sideKey:  undefined
```

You can see the data on the tangle here https://utils.iota.org/mam/FJG9KMOJUAZCTHA9MYDNTPGUSRNMUHLUQW9J9PQFYPLAXYIAKPRZIJSDULJZIXHFL99JGZCV9KBFKR9KF/public/undefined/devnet

Do you have an example of a MAM channel root that it fails on ?

**Comment by johnpeng968** [comment] 2019-12-30 15:58
Hi Martyn,

Thank you for the prompt response.
It seems to me that the first time of the "root" key is correct, but the
second time of iteration, the "root" becomes undefined (as I can tell from
the console log). The declaration of "let root;" in global didn't help to
keep the value, which may result in second time of Mam.fetch() failed.
Please correct me if I am wrong.

Best,
John


Martyn Janes <notifications@github.com> 於 2019年12月30日 週一 下午7:57寫道：

**Comment by johnpeng968** [comment] 2019-12-30 16:54
FYI.
Here are some of the root keys that don't work for me.
JUEHGMNEXSMNCOWLFWERKKDBZLYYXHHBRFVFLYOYSHG9AZMZKMIBIMGEGXQYKSPVZFLPBNHJWCW9KKJFK
EKEZKGAJFKTHZFHEDTEB9RYCLWJBOFYBFSJRPFSOZPRZWVMVZPNALXPJSETMAYLBMZHFUDQHBVGGFAEKL
KGMUKCDTTKXCBZZQQMHDYREDX9RCRB9NAREWFTGTSSQMRMRKKPRLFBJL9LFIUGMAZALQAOZMPDLGNBDMQ

Martyn Janes <notifications@github.com> 於 2019年12月30日 週一 下午7:57寫道：

**Comment by obany** [comment] 2019-12-31 08:13
I think it may actually be the publishing the data that is not working.

If you are running in public mode then the roots are the same as the tangle addresses, so we should see data at the following locations:

https://utils.iota.org/address/JUEHGMNEXSMNCOWLFWERKKDBZLYYXHHBRFVFLYOYSHG9AZMZKMIBIMGEGXQYKSPVZFLPBNHJWCW9KKJFK/devnet
https://utils.iota.org/address/EKEZKGAJFKTHZFHEDTEB9RYCLWJBOFYBFSJRPFSOZPRZWVMVZPNALXPJSETMAYLBMZHFUDQHBVGGFAEKL/devnet
https://utils.iota.org/address/KGMUKCDTTKXCBZZQQMHDYREDX9RCRB9NAREWFTGTSSQMRMRKKPRLFBJL9LFIUGMAZALQAOZMPDLGNBDMQ/devnet

But I can't see transactions on any of those addresses.

**Comment by johnpeng968** [comment] 2019-12-31 09:08
I changed the mode from 'public' to 'restricted' with a sidekey. However,
the problem is still there.
I can't fetch the MAM message using MAM subscriber tool.
Here is code of the sending side and its output log is also attached.
Hope this helps!

const SerialPort = require('serialport')
const moment = require('moment')
const Mam = require('@iota/mam')
const { asciiToTrytes } = require('@iota/converter')

const MODE = 'restricted'; // public, private or restricted
//const MODE = 'public'; // public, private or restricted
const SIDEKEY = 'rock64'; // Enter only ASCII characters. Used only in
restricted mode
const SECURITYLEVEL = 3; // 1, 2 or 3

const PORTNAME = '/dev/ttyACM0';

const port = new SerialPort(PORTNAME, {
    baudRate: 9600,
    autoOpen: true
});

const Readline = SerialPort.parsers.Readline;
const parser = port.pipe(new Readline({ delimiter: '\r\n' }));
// Initialise MAM State

let mamState = Mam.init('https://nodes.devnet.thetangle.org:443')
console.log ('[DEBUG 0] Mam.init...');
mamState = Mam.changeMode(mamState, 'public')

// Set channel mode
if (MODE == 'restricted') {

    const key = asciiToTrytes(SIDEKEY);
    mamState = Mam.changeMode(mamState, MODE, key);
}
 else {
    mamState = Mam.changeMode(mamState, MODE);
}

// Publish to tangle
const publish = async packet => {
    // Create MAM Payload
    // Convert the JSON to trytes and create a MAM message
    const trytes = asciiToTrytes(packet);
    const message = Mam.create(mamState, trytes);

    // Save new mamState
    mamState = message.state;
    console.log('[DEBUG 1 Mam.create...] Root: ', message.root);
    console.log('[DEBUG 2 Mam.create...] Address: ', message.address);

    // Attach the payload.
    console.log('[ DEBUG 3 Mam.attach...]');
    await Mam.attach(message.payload, message.address, 3, 9)
    return message.root
}

// Serial port library events
port.on('open', showPortOpen);
parser.on('data', readSerialData);
port.on('close', showPortClose);
port.on('error', showError);

// Callback functions
function showPortOpen() {
    console.log('Serial port open. Data rate: ' + port.baudRate);
}

async function readSerialData(data){

    // Create JSON object:
    // Convert Arduino received data:  temp: 26.00C, humidity: 21.00%
    // to
    // json = { dateTime: '15/07/2018 10:57:35', data: { temp: '26.00C',
humidity: '21.00%' } }
    //
    let json = {};

    const dateTime = moment().utc().format('DD/MM/YYYY hh:mm:ss');
    json['dateTime'] = dateTime;
        json['data'] = `{${data}}`;

    console.log('[DEBUG 4] Publishing json = ',json);
    const root = await publish(json);
}

function showPortClose() {
    console.log('Serial port closed.');
}

function showError(error) {
   console.log('Serial port error: ' + error);
}

Output log:
[DEBUG 0] Mam.init...
Serial port open. Data rate: 9600
[DEBUG 4] Publishing json =  { dateTime: '31/12/2019 08:56:58',
  data: '{00%  Temperature: 23.40°C 74.12°F  Heat index: 23.39°C 74.10°F}' }
[DEBUG 1 Mam.create...] Root:
 ZLUD9KJBBKFREOIWFXSRIRUJLPNHEEFPFHQKOHBLBHMVPKENW9HIIBLY9LZHXKKHBLWBRHTUGJWRCLRMU
[DEBUG 2 Mam.create...] Address:
 BF9ZUTATIGTJJXONSBKJNU99KJXPBEJIXHNDGFJTKIRGJNGKYCAPYTNEPQEFFEQPWYGBY9WZNFBLYSMID
[ DEBUG 3 Mam.attach...]
[DEBUG 4] Publishing json =  { dateTime: '31/12/2019 08:57:03', data:
'{DHTxx test!}' }
[DEBUG 1 Mam.create...] Root:
 RXJB9WJXEKEXZTPDRLBXYXTKYECSIRKESNFTDOQNHS9LS9DYOMPQCO9YSAHPWIHTVX9XSUQZBTMAYKTPA
[DEBUG 2 Mam.create...] Address:
 SOIMCJMROVEXETWGDAGZAEGSLOFWWDOBDQJYCRRWMWCUMWJSRAP9PJSKNYIGUDGZNYTWRC9OGICLCNNEM
[ DEBUG 3 Mam.attach...]
[DEBUG 4] Publishing json =  { dateTime: '31/12/2019 08:57:07',
  data: '{Humidity: 61.00%  Temperature: 23.40°C 74.12°F  Heat index:
23.39°C 74.10°F}' }
[DEBUG 1 Mam.create...] Root:
 NQPMKUEHXAPXGRLFFBCJPNB9KOIFRVGOEUAXMTZXPXSYFXIEELMBLQUHQWIFRLFOEVOKIUQTYCSFSTMXA
[DEBUG 2 Mam.create...] Address:
 SUJDMAFOIFVRYWDHMFXH9NIHQJFXMDGK9SHLWMIDFHA9C9URNERL9EGKMIKDWSSWQQHQSNRDLLZULIAPT
[ DEBUG 3 Mam.attach...]
[DEBUG 4] Publishing json =  { dateTime: '31/12/2019 08:57:10',
  data: '{Humidity: 62.00%  Temperature: 23.40°C 74.12°F  Heat index:
23.41°C 74.15°F}' }
[DEBUG 1 Mam.create...] Root:
 RJYIJSDOUJUTOSGQHISJAZMYIVQVHAYWSXEUMBURBSZRRTYNNB9MEIYKBXYWVZJUQLSWBTDRVHZQAVDNO
[DEBUG 2 Mam.create...] Address:
 QI9PHZ9OPYMSAYREXWKBVZSKGGENTOTRI9VADGWNPQXBHKVMKTPDHESKXOWVXATPEZZCUXM9RHVEYWBDP
[ DEBUG 3 Mam.attach...]
[DEBUG 4] Publishing json =  { dateTime: '31/12/2019 08:57:19',
  data: '{Humidity: 61.00%  Temperature: 23.40°C 74.12°F  Heat index:
23.39°C 74.10°F}' }
^C

Martyn Janes <notifications@github.com> 於 2019年12月31日 週二 下午4:13寫道：

**Comment by obany** [comment] 2019-12-31 09:15
You also changed the security level to 3 which is not support by the utils site.

Can you simplify and use public mode, security level 2.

**Comment by johnpeng968** [comment] 2019-12-31 09:35
Still doesn't work...

Martyn Janes <notifications@github.com> 於 2019年12月31日 週二 下午5:15寫道：

**Comment by obany** [comment] 2019-12-31 09:46
Can you post the roots that don't work ?

**Comment by johnpeng968** [comment] 2019-12-31 09:54
VTXFAIPQDISPWZAUSLAZWIMFZNOYLCJTKMPS9EPOIIQDNGJJXYBMFRAFUMEB9MMCWSFMXJAPKEOZQWVFF
ZFWKBZHLNAOZWH9KJGZEJEROOYVCXXRGZTO9IUBUWFE9TZSFKA9LDXGGTXXBEJPK9GBYORNSSMSVVKPZX
VJQT9PTGSX9TOXWSSYYNANLBTYRWIUDIOIPBEAPOPWEWXKXUDYJCRTMUMKTJBSQLPDBMSYAQCPSTZVSNV

Martyn Janes <notifications@github.com> 於 2019年12月31日 週二 下午5:46寫道：

**Comment by obany** [comment] 2019-12-31 10:04
I can't find any sign of data posted on those roots

https://utils.iota.org/mam/VTXFAIPQDISPWZAUSLAZWIMFZNOYLCJTKMPS9EPOIIQDNGJJXYBMFRAFUMEB9MMCWSFMXJAPKEOZQWVFF/public/undefined/devnet
https://utils.iota.org/address/VTXFAIPQDISPWZAUSLAZWIMFZNOYLCJTKMPS9EPOIIQDNGJJXYBMFRAFUMEB9MMCWSFMXJAPKEOZQWVFF/devnet
https://thetangle.org/mam/VTXFAIPQDISPWZAUSLAZWIMFZNOYLCJTKMPS9EPOIIQDNGJJXYBMFRAFUMEB9MMCWSFMXJAPKEOZQWVFF
https://devnet.thetangle.org/search/VTXFAIPQDISPWZAUSLAZWIMFZNOYLCJTKMPS9EPOIIQDNGJJXYBMFRAFUMEB9MMCWSFMXJAPKEOZQWVFF

https://utils.iota.org/mam/ZFWKBZHLNAOZWH9KJGZEJEROOYVCXXRGZTO9IUBUWFE9TZSFKA9LDXGGTXXBEJPK9GBYORNSSMSVVKPZX/public/undefined/devnet
https://utils.iota.org/address/ZFWKBZHLNAOZWH9KJGZEJEROOYVCXXRGZTO9IUBUWFE9TZSFKA9LDXGGTXXBEJPK9GBYORNSSMSVVKPZX/devnet
https://thetangle.org/mam/ZFWKBZHLNAOZWH9KJGZEJEROOYVCXXRGZTO9IUBUWFE9TZSFKA9LDXGGTXXBEJPK9GBYORNSSMSVVKPZX
https://devnet.thetangle.org/search/ZFWKBZHLNAOZWH9KJGZEJEROOYVCXXRGZTO9IUBUWFE9TZSFKA9LDXGGTXXBEJPK9GBYORNSSMSVVKPZX

https://utils.iota.org/mam/VJQT9PTGSX9TOXWSSYYNANLBTYRWIUDIOIPBEAPOPWEWXKXUDYJCRTMUMKTJBSQLPDBMSYAQCPSTZVSNV/public/undefined/devnet
https://utils.iota.org/address/VJQT9PTGSX9TOXWSSYYNANLBTYRWIUDIOIPBEAPOPWEWXKXUDYJCRTMUMKTJBSQLPDBMSYAQCPSTZVSNV/devnet
https://thetangle.org/mam/VJQT9PTGSX9TOXWSSYYNANLBTYRWIUDIOIPBEAPOPWEWXKXUDYJCRTMUMKTJBSQLPDBMSYAQCPSTZVSNV
https://devnet.thetangle.org/search/VJQT9PTGSX9TOXWSSYYNANLBTYRWIUDIOIPBEAPOPWEWXKXUDYJCRTMUMKTJBSQLPDBMSYAQCPSTZVSNV

Without being able to see some data posted I can not really help any further. If you can create a public channel that is viewable on either of the explore sites then I can continue to help.

**Comment by johnpeng968** [comment] 2019-12-31 10:13
Thanks for the help. Let me see how can I setup a public test environment
that allow us to continue with.

Martyn Janes <notifications@github.com> 於 2019年12月31日 週二 下午6:04寫道：

**Comment by johnpeng968** [comment] 2020-01-01 13:15
CPGLRKWTPVFFAGHGCWSQOJINKXFRYP9OFN9SQKDKMSBWGKNWJVBRFJRVXAATDUDMUTKIYFCGGSOQNPPWG

These address show message trytes without data. Any idea?

john peng <johnpeng968@gmail.com> 於 2019年12月31日 週二 下午6:13寫道：

**Comment by johnpeng968** [comment] 2020-01-02 08:31
All the issues have been resolved by change the sketch on the MCU side.

Thanks!

john peng <johnpeng968@gmail.com> 於 2020年1月1日 週三 下午9:15寫道：
